#!/usr/bin/env bash
# Verify subagent output schema compliance
# Receives tool output via stdin as JSON

set -euo pipefail

LOG_DIR="${CLAUDE_PROJECT_ROOT:-.}/.claude/plugins/nexus-orchestrator/logs"
DEVIATION_FILE="${CLAUDE_PROJECT_ROOT:-.}/.claude/plugins/nexus-orchestrator/deviations/log.yaml"
mkdir -p "$LOG_DIR"
mkdir -p "$(dirname "$DEVIATION_FILE")"

LOG_FILE="$LOG_DIR/verify-$(date +%Y%m%d).log"

# Read stdin (tool output JSON)
INPUT=$(cat)

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Extract the result text
RESULT=$(echo "$INPUT" | jq -r '.tool_result // ""' 2>/dev/null)

# Check for required YAML fields in executor response
SCHEMA_VALID=true
MISSING_FIELDS=""

for field in "understood:" "approach:" "observations:" "blockers:" "output:" "confidence:" "evidence:"; do
  if ! echo "$RESULT" | grep -q "$field"; then
    SCHEMA_VALID=false
    MISSING_FIELDS="$MISSING_FIELDS $field"
  fi
done

# Log verification
cat >> "$LOG_FILE" << EOF
---
timestamp: $TIMESTAMP
event: verify
schema_valid: $SCHEMA_VALID
missing_fields: [$MISSING_FIELDS ]
result_length: ${#RESULT}
---
EOF

# If schema invalid, log deviation (but don't block - just warn)
if [ "$SCHEMA_VALID" = "false" ]; then
  # Get next deviation ID
  if [ -f "$DEVIATION_FILE" ]; then
    LAST_ID=$(grep -o 'id: [0-9]*' "$DEVIATION_FILE" | tail -1 | grep -o '[0-9]*' || echo "0")
    NEXT_ID=$((LAST_ID + 1))
  else
    NEXT_ID=1
    echo "# Deviation Log" > "$DEVIATION_FILE"
    echo "# Auto-generated by verify-output hook" >> "$DEVIATION_FILE"
    echo "" >> "$DEVIATION_FILE"
  fi

  cat >> "$DEVIATION_FILE" << EOF
- id: $NEXT_ID
  timestamp: $TIMESTAMP
  expected: "YAML response with fields: understood, approach, observations, blockers, output, confidence, evidence"
  actual: "Missing fields:$MISSING_FIELDS"
  root_cause: schema_violation
  fix: |
    Ensure executor subagent prompt emphasizes YAML-only response.
    Add explicit schema reminder to task dispatch.

EOF

  # Output warning context (doesn't block, just informs)
  cat << EOF
{
  "hookSpecificOutput": {
    "hookEventName": "PostToolUse",
    "additionalContext": "[ORCHESTRATOR] Schema violation detected. Missing fields:$MISSING_FIELDS. See deviations/log.yaml."
  }
}
EOF
else
  # Schema valid - no additional output needed
  echo '{}'
fi

exit 0
